name: MSYS2
on: [push, pull_request]

jobs:
  msys2-x64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-python mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-ninja mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-glfw mingw-w64-ucrt-x86_64-libepoxy mingw-w64-ucrt-x86_64-pybind11 mingw-w64-ucrt-x86_64-libiconv
      - name: CI-Build
        run: |
          ./ci-build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/*.bat
            build/*.dll
            build/*.exe
            build/venv/
